services:
  website:
    image: nginx:alpine
    container_name: sweater
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sweater.rule=Host(`sweater.maksimlebedev.ru`)"
      - "traefik.http.routers.sweater.tls=true"
      - "traefik.http.routers.sweater.tls.certresolver=letsencrypt"
      - "traefik.http.services.sweater.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true