version: "3.7"

services:
  sweater_maksimlebedev:
    image: php:7.2-apache
    container_name: sweater_maksimlebedev
    expose:
      - 80
      - 443
    volumes:
      - ./public:/var/www/html
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL

networks:
  default:
    name: nginx-proxy
